In [1]:
import numpy as np

Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

In [33]:
A = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1] ])
B = A.T
A@B
#она же является частным случаем Верхнетреугольная, ортогональная и Нижнетреугольная, ортогональная

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Матрица, у которой определитель = 1, и все элементы не равны 0

In [128]:
C = np.array([[2, 1], [1, 1] ])
np.linalg.det(C)

1.0

In [131]:
m = np.array([[2, 2],
              [1, 3]])
np.linalg.eig(m)

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

Собственные числа 1 и 4, вектора соответственно строчки в массиве